### ISSUE TITLE
working with electron

### ISSUE THREAD

**Issue by mmahalwy** [mdlawson/piping#11]
I keep getting error:
```
[piping] can't execute file: /Users/mmahalwy/Desktop/code/chill/chill-frontend/electron.js
[piping] error given was: Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.module._load (/Users/mmahalwy/Desktop/code/chill/chill-frontend/node_modules/piping/lib/launcher.js:24:23)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/mmahalwy/Desktop/code/chill/chill-frontend/electron.js:3:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Module._load (module.js:313:12)
```

When trying to make this work with electron. 
```
const electron = require('electron');
const app = electron.app;  // Module to control application life.
const BrowserWindow = electron.BrowserWindow;  // Module to create native browser window.
```

My ignore is not working...
```
if (!require('piping')({
      hook: true,
      ignore: /(electron|\/\.|~$|\.json|\.scss$)/
    })) {
    return;
  }
```

**Comment by mntnoe** [comment]
What behavior do you get if you rename chill/chill-frontend/electron.js?

**Comment by mmahalwy** [comment]
@mntnoe the problem is that when running code via electron, it almost polyfills or has an alias for `require('electron')` to `require('electron-prebuilt')` but i cannot just use prebuilt

**Comment by mntnoe** [comment]
I don't think it is possible to use piping directly from the electron executable. However, I looked at the `electron-quick-start` repo, and was able to get piping working by making an adapted version of the cli.js script:

    if (!require('piping')()) { return; }
    
    const electron = require('electron-prebuilt');
    const proc = require('child_process')
    const child = proc.spawn(electron, process.argv.slice(2), {stdio: 'inherit'})
    child.on('close', function (code) { process.exit(code) })

Instead of running the app as

    electron main.js

use

    node run.js main.js

Where run.js is the name of your electron wrapper. You can then also still use the default electron executable for production.

**Comment by mmahalwy** [comment]
ah interesting. Will give it a try @mntnoe
